version: '3.8'

services:
  # PostgreSQL Database (same as production)
  postgres:
    image: postgres:15-alpine
    container_name: stratavision-postgres-dev
    env_file:
      - .env
      - .env.local
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-stratavision_dev}
      POSTGRES_USER: ${POSTGRES_USER:-stratavision}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - stratavision-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stratavision"]
      interval: 10s
      timeout: 5s
      retries: 5

  # NextJS Development Server
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: stratavision-app-dev
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
      - .env.local
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-stratavision}:${POSTGRES_PASSWORD}@postgres:5432/stratavision_dev?schema=public
    ports:
      - "3000:3000"
    networks:
      - stratavision-network
    volumes:
      # Mount source code for hot reload
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped

networks:
  stratavision-network:
    driver: bridge

volumes:
  postgres_dev_data: 